/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package edu.zuhaib.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Person extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Person\",\"namespace\":\"edu.zuhaib.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"username\",\"type\":[\"string\",\"null\"]},{\"name\":\"email_address\",\"type\":[\"string\",\"null\"]},{\"name\":\"phone_number\",\"type\":[\"string\",\"null\"]},{\"name\":\"first_name\",\"type\":[\"string\",\"null\"]},{\"name\":\"last_name\",\"type\":[\"string\",\"null\"]},{\"name\":\"middle_name\",\"type\":[\"string\",\"null\"]},{\"name\":\"sex\",\"type\":[\"string\",\"null\"]},{\"name\":\"birthdate\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence username;
  @Deprecated public java.lang.CharSequence email_address;
  @Deprecated public java.lang.CharSequence phone_number;
  @Deprecated public java.lang.CharSequence first_name;
  @Deprecated public java.lang.CharSequence last_name;
  @Deprecated public java.lang.CharSequence middle_name;
  @Deprecated public java.lang.CharSequence sex;
  @Deprecated public java.lang.CharSequence birthdate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Person() {}

  /**
   * All-args constructor.
   */
  public Person(java.lang.Integer id, java.lang.CharSequence username, java.lang.CharSequence email_address, java.lang.CharSequence phone_number, java.lang.CharSequence first_name, java.lang.CharSequence last_name, java.lang.CharSequence middle_name, java.lang.CharSequence sex, java.lang.CharSequence birthdate) {
    this.id = id;
    this.username = username;
    this.email_address = email_address;
    this.phone_number = phone_number;
    this.first_name = first_name;
    this.last_name = last_name;
    this.middle_name = middle_name;
    this.sex = sex;
    this.birthdate = birthdate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return username;
    case 2: return email_address;
    case 3: return phone_number;
    case 4: return first_name;
    case 5: return last_name;
    case 6: return middle_name;
    case 7: return sex;
    case 8: return birthdate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: username = (java.lang.CharSequence)value$; break;
    case 2: email_address = (java.lang.CharSequence)value$; break;
    case 3: phone_number = (java.lang.CharSequence)value$; break;
    case 4: first_name = (java.lang.CharSequence)value$; break;
    case 5: last_name = (java.lang.CharSequence)value$; break;
    case 6: middle_name = (java.lang.CharSequence)value$; break;
    case 7: sex = (java.lang.CharSequence)value$; break;
    case 8: birthdate = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'username' field.
   */
  public java.lang.CharSequence getUsername() {
    return username;
  }

  /**
   * Sets the value of the 'username' field.
   * @param value the value to set.
   */
  public void setUsername(java.lang.CharSequence value) {
    this.username = value;
  }

  /**
   * Gets the value of the 'email_address' field.
   */
  public java.lang.CharSequence getEmailAddress() {
    return email_address;
  }

  /**
   * Sets the value of the 'email_address' field.
   * @param value the value to set.
   */
  public void setEmailAddress(java.lang.CharSequence value) {
    this.email_address = value;
  }

  /**
   * Gets the value of the 'phone_number' field.
   */
  public java.lang.CharSequence getPhoneNumber() {
    return phone_number;
  }

  /**
   * Sets the value of the 'phone_number' field.
   * @param value the value to set.
   */
  public void setPhoneNumber(java.lang.CharSequence value) {
    this.phone_number = value;
  }

  /**
   * Gets the value of the 'first_name' field.
   */
  public java.lang.CharSequence getFirstName() {
    return first_name;
  }

  /**
   * Sets the value of the 'first_name' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.first_name = value;
  }

  /**
   * Gets the value of the 'last_name' field.
   */
  public java.lang.CharSequence getLastName() {
    return last_name;
  }

  /**
   * Sets the value of the 'last_name' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.last_name = value;
  }

  /**
   * Gets the value of the 'middle_name' field.
   */
  public java.lang.CharSequence getMiddleName() {
    return middle_name;
  }

  /**
   * Sets the value of the 'middle_name' field.
   * @param value the value to set.
   */
  public void setMiddleName(java.lang.CharSequence value) {
    this.middle_name = value;
  }

  /**
   * Gets the value of the 'sex' field.
   */
  public java.lang.CharSequence getSex() {
    return sex;
  }

  /**
   * Sets the value of the 'sex' field.
   * @param value the value to set.
   */
  public void setSex(java.lang.CharSequence value) {
    this.sex = value;
  }

  /**
   * Gets the value of the 'birthdate' field.
   */
  public java.lang.CharSequence getBirthdate() {
    return birthdate;
  }

  /**
   * Sets the value of the 'birthdate' field.
   * @param value the value to set.
   */
  public void setBirthdate(java.lang.CharSequence value) {
    this.birthdate = value;
  }

  /** Creates a new Person RecordBuilder */
  public static edu.zuhaib.avro.Person.Builder newBuilder() {
    return new edu.zuhaib.avro.Person.Builder();
  }
  
  /** Creates a new Person RecordBuilder by copying an existing Builder */
  public static edu.zuhaib.avro.Person.Builder newBuilder(edu.zuhaib.avro.Person.Builder other) {
    return new edu.zuhaib.avro.Person.Builder(other);
  }
  
  /** Creates a new Person RecordBuilder by copying an existing Person instance */
  public static edu.zuhaib.avro.Person.Builder newBuilder(edu.zuhaib.avro.Person other) {
    return new edu.zuhaib.avro.Person.Builder(other);
  }
  
  /**
   * RecordBuilder for Person instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Person>
    implements org.apache.avro.data.RecordBuilder<Person> {

    private int id;
    private java.lang.CharSequence username;
    private java.lang.CharSequence email_address;
    private java.lang.CharSequence phone_number;
    private java.lang.CharSequence first_name;
    private java.lang.CharSequence last_name;
    private java.lang.CharSequence middle_name;
    private java.lang.CharSequence sex;
    private java.lang.CharSequence birthdate;

    /** Creates a new Builder */
    private Builder() {
      super(edu.zuhaib.avro.Person.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(edu.zuhaib.avro.Person.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.username)) {
        this.username = data().deepCopy(fields()[1].schema(), other.username);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.email_address)) {
        this.email_address = data().deepCopy(fields()[2].schema(), other.email_address);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.phone_number)) {
        this.phone_number = data().deepCopy(fields()[3].schema(), other.phone_number);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.first_name)) {
        this.first_name = data().deepCopy(fields()[4].schema(), other.first_name);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.last_name)) {
        this.last_name = data().deepCopy(fields()[5].schema(), other.last_name);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.middle_name)) {
        this.middle_name = data().deepCopy(fields()[6].schema(), other.middle_name);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.sex)) {
        this.sex = data().deepCopy(fields()[7].schema(), other.sex);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.birthdate)) {
        this.birthdate = data().deepCopy(fields()[8].schema(), other.birthdate);
        fieldSetFlags()[8] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Person instance */
    private Builder(edu.zuhaib.avro.Person other) {
            super(edu.zuhaib.avro.Person.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.username)) {
        this.username = data().deepCopy(fields()[1].schema(), other.username);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.email_address)) {
        this.email_address = data().deepCopy(fields()[2].schema(), other.email_address);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.phone_number)) {
        this.phone_number = data().deepCopy(fields()[3].schema(), other.phone_number);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.first_name)) {
        this.first_name = data().deepCopy(fields()[4].schema(), other.first_name);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.last_name)) {
        this.last_name = data().deepCopy(fields()[5].schema(), other.last_name);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.middle_name)) {
        this.middle_name = data().deepCopy(fields()[6].schema(), other.middle_name);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.sex)) {
        this.sex = data().deepCopy(fields()[7].schema(), other.sex);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.birthdate)) {
        this.birthdate = data().deepCopy(fields()[8].schema(), other.birthdate);
        fieldSetFlags()[8] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public edu.zuhaib.avro.Person.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public edu.zuhaib.avro.Person.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'username' field */
    public java.lang.CharSequence getUsername() {
      return username;
    }
    
    /** Sets the value of the 'username' field */
    public edu.zuhaib.avro.Person.Builder setUsername(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.username = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'username' field has been set */
    public boolean hasUsername() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'username' field */
    public edu.zuhaib.avro.Person.Builder clearUsername() {
      username = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'email_address' field */
    public java.lang.CharSequence getEmailAddress() {
      return email_address;
    }
    
    /** Sets the value of the 'email_address' field */
    public edu.zuhaib.avro.Person.Builder setEmailAddress(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.email_address = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'email_address' field has been set */
    public boolean hasEmailAddress() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'email_address' field */
    public edu.zuhaib.avro.Person.Builder clearEmailAddress() {
      email_address = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'phone_number' field */
    public java.lang.CharSequence getPhoneNumber() {
      return phone_number;
    }
    
    /** Sets the value of the 'phone_number' field */
    public edu.zuhaib.avro.Person.Builder setPhoneNumber(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.phone_number = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'phone_number' field has been set */
    public boolean hasPhoneNumber() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'phone_number' field */
    public edu.zuhaib.avro.Person.Builder clearPhoneNumber() {
      phone_number = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'first_name' field */
    public java.lang.CharSequence getFirstName() {
      return first_name;
    }
    
    /** Sets the value of the 'first_name' field */
    public edu.zuhaib.avro.Person.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.first_name = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'first_name' field has been set */
    public boolean hasFirstName() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'first_name' field */
    public edu.zuhaib.avro.Person.Builder clearFirstName() {
      first_name = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'last_name' field */
    public java.lang.CharSequence getLastName() {
      return last_name;
    }
    
    /** Sets the value of the 'last_name' field */
    public edu.zuhaib.avro.Person.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.last_name = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'last_name' field has been set */
    public boolean hasLastName() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'last_name' field */
    public edu.zuhaib.avro.Person.Builder clearLastName() {
      last_name = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'middle_name' field */
    public java.lang.CharSequence getMiddleName() {
      return middle_name;
    }
    
    /** Sets the value of the 'middle_name' field */
    public edu.zuhaib.avro.Person.Builder setMiddleName(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.middle_name = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'middle_name' field has been set */
    public boolean hasMiddleName() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'middle_name' field */
    public edu.zuhaib.avro.Person.Builder clearMiddleName() {
      middle_name = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'sex' field */
    public java.lang.CharSequence getSex() {
      return sex;
    }
    
    /** Sets the value of the 'sex' field */
    public edu.zuhaib.avro.Person.Builder setSex(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.sex = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'sex' field has been set */
    public boolean hasSex() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'sex' field */
    public edu.zuhaib.avro.Person.Builder clearSex() {
      sex = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'birthdate' field */
    public java.lang.CharSequence getBirthdate() {
      return birthdate;
    }
    
    /** Sets the value of the 'birthdate' field */
    public edu.zuhaib.avro.Person.Builder setBirthdate(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.birthdate = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'birthdate' field has been set */
    public boolean hasBirthdate() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'birthdate' field */
    public edu.zuhaib.avro.Person.Builder clearBirthdate() {
      birthdate = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    public Person build() {
      try {
        Person record = new Person();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.username = fieldSetFlags()[1] ? this.username : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.email_address = fieldSetFlags()[2] ? this.email_address : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.phone_number = fieldSetFlags()[3] ? this.phone_number : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.first_name = fieldSetFlags()[4] ? this.first_name : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.last_name = fieldSetFlags()[5] ? this.last_name : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.middle_name = fieldSetFlags()[6] ? this.middle_name : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.sex = fieldSetFlags()[7] ? this.sex : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.birthdate = fieldSetFlags()[8] ? this.birthdate : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
